# Modelo de Ia (Gaussian)

In [96]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import  train_test_split,KFold,cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer,make_column_selector
from sklearn.ensemble import RandomForestClassifier

In [97]:
df = pd.read_excel('../base/incluses_tratado.xlsx')

display(df.head(5))

Participante da Comunidade LGBTQIA+      Faixa Etária Identidade de Gênero  \
0                                 Sim  Menos de 18 anos     Mulher cisgênero   
1                                 Sim  Menos de 18 anos     Mulher cisgênero   
2                                 Sim  Menos de 18 anos     Mulher cisgênero   
3                                 Sim  Menos de 18 anos     Mulher cisgênero   
4                                 Sim  Menos de 18 anos    Homem transgênero   

      Orientação Sexual   Cidade/Estado  \
0           Homossexual  Região Sudeste   
1           Homossexual  Região Sudeste   
2             Pansexual    Região Norte   
3             Bissexual  Região Sudeste   
4  Prefiro não informar  Região Sudeste   

                              Escolaridade  \
0  Ensino Fundamental completo ou cursando   
1  Ensino Fundamental completo ou cursando   
2  Ensino Fundamental completo ou cursando   
3  Ensino Fundamental completo ou cursando   
4                                   Nenhum   

  Usa Apps para Oportunidades de Emprego?  \
0                                     Sim   
1                         Tenho interesse   
2                                     Não   
3                                     Não   
4                                     Não   

                               Preferência de Cursos  \
0                             Prefiro cursos on-line   
1  Não tenho preferência, pode ser on-line ou pre...   
2  Não tenho preferência, pode ser on-line ou pre...   
3  Não tenho preferência, pode ser on-line ou pre...   
4  Não tenho preferência, pode ser on-line ou pre...   

  Desafios de Emprego por Gênero Interesse em Empreender  \
0                            Sim                     Não   
1                            Sim                     Não   
2                            Não                  Talvez   
3                            Sim                     Não   
4                            Sim                     Sim   

  Situação no Mercado de Trabalho Usa Redes Sociais?  \
0                   Empregado (a)                Sim   
1                   Empregado (a)                Sim   
2                   Empregado (a)                Sim   
3                   Empregado (a)                Sim   
4                Desempregado (a)                Sim   

  Finalidade do Uso do App Incluses  
0                       Todos acima  
1                  Não usaria o app  
2      Fazer cursos de qualificação  
3                  Não usaria o app  
4      Fazer cursos de qualificação

In [98]:
df_resposta = df['Finalidade do Uso do App Incluses']
df_atributo = df.iloc[:, :-1]

#Resposta
label_encoder = LabelEncoder()

#Treino
preprocessador = ColumnTransformer(
    transformers=[
        ('ordinal_encoder', OrdinalEncoder(), make_column_selector(dtype_include=['object','bool'])),
    ],
    remainder='passthrough',
    verbose_feature_names_out= False 
)

In [99]:
df_atributo = pd.DataFrame(preprocessador.fit_transform(df_atributo), columns=preprocessador.get_feature_names_out())
df_resposta = pd.DataFrame(label_encoder.fit_transform(df_resposta))


smote = SMOTE(random_state=42,k_neighbors=2)
df_atributo, df_resposta = smote.fit_resample(df_atributo, df_resposta)

In [100]:
df_atributos_treino, df_atributos_teste, df_resposta_treino, df_resposta_teste = train_test_split(df_atributo, df_resposta, test_size=0.25, random_state=12)

atributos_treino = df_atributos_treino.values
resposta_treino = df_resposta_treino.values

atributos_teste = df_atributos_teste.values
resposta_teste = df_resposta_teste.values




# Aplicar SMOTE no conjunto de treino, ajustando o número de vizinhos para evitar o erro
# smote = SMOTE(random_state=12, k_neighbors=1)
# atributos_treino, resposta_treino = smote.fit_resample(df_atributos_treino, df_resposta_treino)

# Convertendo para arrays
atributos_teste = df_atributos_teste.values
resposta_teste = df_resposta_teste.values

In [101]:
classificador_bayes = GaussianNB()
modelo = classificador_bayes.fit(df_atributos_treino, df_resposta_treino)

probabilidades = classificador_bayes.predict_proba(atributos_teste)
classificacao = classificador_bayes.predict(atributos_teste)

c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [102]:
# print("Probabilidades das classes para os dados de teste:\n", probabilidades)
# print("Classificação dos dados de teste:\n", classificacao)

taxa_de_acerto = accuracy_score(resposta_teste, classificacao)
print("Taxa de acerto", taxa_de_acerto)
print("\nRelatório de Classificação:\n", classification_report(resposta_teste, classificacao))
print("Matriz de Confusão:\n", confusion_matrix(resposta_teste, classificacao))

Taxa de acerto 0.6

Relatório de Classificação:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       0.00      0.00      0.00         3
           2       0.80      0.67      0.73         6
           3       0.67      1.00      0.80         2
           4       0.38      0.50      0.43         6

    accuracy                           0.60        20
   macro avg       0.57      0.63      0.59        20
weighted avg       0.57      0.60      0.58        20

Matriz de Confusão:
 [[3 0 0 0 0]
 [0 0 0 0 3]
 [0 0 4 0 2]
 [0 0 0 2 0]
 [0 1 1 1 3]]


In [103]:
numfolds = 5
gnb = GaussianNB()

kf = KFold(n_splits=numfolds, shuffle=True, random_state=31)

validaçãoCruzada = cross_val_score(gnb, df_atributo, df_resposta, cv=kf)
media = validaçãoCruzada.mean()

print(validaçãoCruzada)
print(media)

[0.4375 0.6875 0.6875 0.625  0.5625]
0.6


c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-pack

In [104]:
predictions = cross_val_predict(gnb, df_atributo, df_resposta, cv=kf)

fold_indices = np.arange(len(predictions)) % numfolds

conf_matrices = [
    confusion_matrix(df_resposta[fold_indices == i], predictions[fold_indices == i])
    for i in range(numfolds)
]

acuracia_matrices = [
    accuracy_score(df_resposta[fold_indices == i], predictions[fold_indices == i])
    for i in range(numfolds)
]

for i, conf_matrix in enumerate(conf_matrices):
    print(f"Fold {i + 1}:\nAcurácia: {round(acuracia_matrices[i]*100)}%\n{conf_matrix}\n")

mean_conf_matrix = np.mean(conf_matrices, axis=0)
mean_acuracia_matrix = np.mean(acuracia_matrices, axis=0)
print("matriz de confusao média:")
print(f"{mean_acuracia_matrix*100:.2f}%")
print(mean_conf_matrix)

Fold 1:
Acurácia: 69%
[[3 0 0 0 0]
 [1 3 0 0 0]
 [1 1 1 0 0]
 [0 0 0 2 0]
 [1 0 1 0 2]]

Fold 2:
Acurácia: 50%
[[3 0 0 0 0]
 [1 1 2 0 0]
 [0 1 2 0 0]
 [0 2 0 2 0]
 [0 1 1 0 0]]

Fold 3:
Acurácia: 62%
[[3 0 0 0 0]
 [0 3 1 0 0]
 [0 0 4 0 0]
 [0 1 1 0 0]
 [0 2 1 0 0]]

Fold 4:
Acurácia: 69%
[[4 0 0 0 0]
 [0 1 0 0 1]
 [0 0 3 0 0]
 [0 2 1 3 0]
 [0 1 0 0 0]]

Fold 5:
Acurácia: 50%
[[3 0 0 0 0]
 [0 1 1 0 0]
 [0 0 3 0 0]
 [0 0 0 1 1]
 [0 2 3 1 0]]

matriz de confusao média:
60.00%
[[3.2 0.  0.  0.  0. ]
 [0.4 1.8 0.8 0.  0.2]
 [0.2 0.4 2.6 0.  0. ]
 [0.  1.  0.4 1.6 0.2]
 [0.2 1.2 1.2 0.2 0.4]]


c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-pack