# Modelo de Ia (Gaussian)

In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import  train_test_split,KFold,cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer,make_column_selector

In [2]:
df = pd.read_excel('../base/Incluses.xlsx')

df = df.drop(columns=['Id', 'Hora de início','Hora de conclusão','Email','Nome','Coluna1'])

display(df.head(5))

Você participa da comunidade LGBTQIA+             Idade            Gênero  \
0                                   Não               NaN               NaN   
1                                   Não               NaN               NaN   
2                                   Sim  Menos de 18 anos  Mulher cisgênero   
3                                   Sim  Menos de 18 anos  Mulher cisgênero   
4                                   Sim  Menos de 18 anos  Mulher cisgênero   

  Orientação Sexual     Localização        Nível de Escolaridade  \
0               NaN             NaN                          NaN   
1               NaN             NaN                          NaN   
2       Homossexual  Região Sudeste  Ensino Fundamental completo   
3       Homossexual  Região Sudeste  Ensino Fundamental completo   
4         Pansexual    Região Norte  Ensino Fundamental completo   

  Você usa aplicativos para procurar oportunidades de emprego?  \
0                                                NaN             
1                                                NaN             
2                                                Sim             
3                                    Tenho interesse             
4                                                Não             

                              Preferência por Cursos  \
0                                                NaN   
1                                                NaN   
2                              Prefiro cursos online   
3  Não tenho preferência, pode ser online ou pres...   
4  Não tenho preferência, pode ser online ou pres...   

  Você já sentiu desafios para entrar no mercado de trabalho devido ao seu gênero  \
0                                                NaN                                
1                                                NaN                                
2                                                Sim                                
3                                                Sim                                
4                                                Não                                

  Você tem interesse em empreender?  \
0                               NaN   
1                               NaN   
2                               Não   
3                               Não   
4                            Talvez   

  Qual é a sua situação diante ao mercado de trabalho?  \
0                                                NaN     
1                                                NaN     
2                                      Empregado (a)     
3                                      Empregado (a)     
4                                      Empregado (a)     

  Você usa redes sociais (exemplo: X, Facebook, Instagram, Youtube)  \
0                                                NaN                  
1                                                NaN                  
2                                                Sim                  
3                                                Sim                  
4                                                Sim                  

  Com quais finalidades você usaria o Aplicativo Incluses  
0                                                NaN       
1                                                NaN       
2                                        Todos acima       
3                                   Não usaria o app       
4                       Fazer cursos de qualificação

In [3]:
display(df.describe())

Você participa da comunidade LGBTQIA+             Idade  \
count                                    162                47   
unique                                     2                 6   
top                                      Não  Menos de 18 anos   
freq                                     115                29   

                  Gênero Orientação Sexual     Localização  \
count                 47                47              47   
unique                 7                 7               5   
top     Mulher cisgênero         Bissexual  Região Sudeste   
freq                  20                16              33   

              Nível de Escolaridade  \
count                            47   
unique                            7   
top     Ensino Fundamental completo   
freq                             16   

       Você usa aplicativos para procurar oportunidades de emprego?  \
count                                                  47             
unique                                                  3             
top                                                   Sim             
freq                                                   23             

                                   Preferência por Cursos  \
count                                                  47   
unique                                                  5   
top     Não tenho preferência, pode ser on-line ou pre...   
freq                                                   20   

       Você já sentiu desafios para entrar no mercado de trabalho devido ao seu gênero  \
count                                                  47                                
unique                                                  2                                
top                                                   Não                                
freq                                                   29                                

       Você tem interesse em empreender?  \
count                                 47   
unique                                 3   
top                               Talvez   
freq                                  19   

       Qual é a sua situação diante ao mercado de trabalho?  \
count                                                  47     
unique                                                  2     
top                                         Empregado (a)     
freq                                                   26     

       Você usa redes sociais (exemplo: X, Facebook, Instagram, Youtube)  \
count                                                  47                  
unique                                                  2                  
top                                                   Sim                  
freq                                                   44                  

       Com quais finalidades você usaria o Aplicativo Incluses  
count                                                  47       
unique                                                  5       
top                                           Todos acima       
freq                                                   16

In [4]:
df = df[df['Você participa da comunidade LGBTQIA+'] == 'Sim']
df['Com quais finalidades você usaria o Aplicativo Incluses'] = df['Com quais finalidades você usaria o Aplicativo Incluses'].replace({"Encontrar oportunidades de emprego": "sim", "Fazer cursos de qualificação": "sim", "Divulgar conteúdos profissionais": "sim",'Divulgar conteúdos profissionais\xa0':"sim" ,"Todos acima": "sim", "Não usaria o app": "não"})

df['Idade'] = df['Idade'].replace({"Menos de 18 anos": "jovem", "18-24 anos": "jovem", "25-34 anos": "adulto",'35-44 anos':"adulto" ,"45-54 anos": "adulto", "55 anos ou mais": "idoso"})


display(df.head(5))
display(df.describe())

Você participa da comunidade LGBTQIA+  Idade             Gênero  \
2                                    Sim  jovem   Mulher cisgênero   
3                                    Sim  jovem   Mulher cisgênero   
4                                    Sim  jovem   Mulher cisgênero   
5                                    Sim  jovem   Mulher cisgênero   
14                                   Sim  jovem  Homem transgênero   

       Orientação Sexual     Localização        Nível de Escolaridade  \
2            Homossexual  Região Sudeste  Ensino Fundamental completo   
3            Homossexual  Região Sudeste  Ensino Fundamental completo   
4              Pansexual    Região Norte  Ensino Fundamental completo   
5              Bissexual  Região Sudeste  Ensino Fundamental completo   
14  Prefiro não informar  Região Sudeste                       Nenhum   

   Você usa aplicativos para procurar oportunidades de emprego?  \
2                                                 Sim             
3                                     Tenho interesse             
4                                                 Não             
5                                                 Não             
14                                                Não             

                               Preferência por Cursos  \
2                               Prefiro cursos online   
3   Não tenho preferência, pode ser online ou pres...   
4   Não tenho preferência, pode ser online ou pres...   
5   Não tenho preferência, pode ser online ou pres...   
14  Não tenho preferência, pode ser on-line ou pre...   

   Você já sentiu desafios para entrar no mercado de trabalho devido ao seu gênero  \
2                                                 Sim                                
3                                                 Sim                                
4                                                 Não                                
5                                                 Sim                                
14                                                Sim                                

   Você tem interesse em empreender?  \
2                                Não   
3                                Não   
4                             Talvez   
5                                Não   
14                               Sim   

   Qual é a sua situação diante ao mercado de trabalho?  \
2                                       Empregado (a)     
3                                       Empregado (a)     
4                                       Empregado (a)     
5                                       Empregado (a)     
14                                   Desempregado (a)     

   Você usa redes sociais (exemplo: X, Facebook, Instagram, Youtube)  \
2                                                 Sim                  
3                                                 Sim                  
4                                                 Sim                  
5                                                 Sim                  
14                                                Sim                  

   Com quais finalidades você usaria o Aplicativo Incluses  
2                                                 sim       
3                                                 não       
4                                                 sim       
5                                                 não       
14                                                sim

Você participa da comunidade LGBTQIA+  Idade            Gênero  \
count                                     47     47                47   
unique                                     1      3                 7   
top                                      Sim  jovem  Mulher cisgênero   
freq                                      47     31                20   

       Orientação Sexual     Localização        Nível de Escolaridade  \
count                 47              47                           47   
unique                 7               5                            7   
top            Bissexual  Região Sudeste  Ensino Fundamental completo   
freq                  16              33                           16   

       Você usa aplicativos para procurar oportunidades de emprego?  \
count                                                  47             
unique                                                  3             
top                                                   Sim             
freq                                                   23             

                                   Preferência por Cursos  \
count                                                  47   
unique                                                  5   
top     Não tenho preferência, pode ser on-line ou pre...   
freq                                                   20   

       Você já sentiu desafios para entrar no mercado de trabalho devido ao seu gênero  \
count                                                  47                                
unique                                                  2                                
top                                                   Não                                
freq                                                   29                                

       Você tem interesse em empreender?  \
count                                 47   
unique                                 3   
top                               Talvez   
freq                                  19   

       Qual é a sua situação diante ao mercado de trabalho?  \
count                                                  47     
unique                                                  2     
top                                         Empregado (a)     
freq                                                   26     

       Você usa redes sociais (exemplo: X, Facebook, Instagram, Youtube)  \
count                                                  47                  
unique                                                  2                  
top                                                   Sim                  
freq                                                   44                  

       Com quais finalidades você usaria o Aplicativo Incluses  
count                                                  47       
unique                                                  2       
top                                                   sim       
freq                                                   41

In [5]:
df_resposta = df['Com quais finalidades você usaria o Aplicativo Incluses']
df_atributo = df.iloc[:, :-1]

#Resposta
label_encoder = LabelEncoder()

#Treino
preprocessador = ColumnTransformer(
    transformers=[
        ('ordinal_encoder', OrdinalEncoder(), make_column_selector(dtype_include=['object','bool'])),
    ],
    remainder='passthrough',
    verbose_feature_names_out= False 
)

In [6]:
df_atributo = pd.DataFrame(preprocessador.fit_transform(df_atributo), columns=preprocessador.get_feature_names_out())
df_resposta = pd.DataFrame(label_encoder.fit_transform(df_resposta))


smote = SMOTE(random_state=12,k_neighbors=1)
df_atributo, df_resposta = smote.fit_resample(df_atributo, df_resposta)

In [7]:
df_atributos_treino, df_atributos_teste, df_resposta_treino, df_resposta_teste = train_test_split(df_atributo, df_resposta, test_size=0.25, random_state=12)

atributos_treino = df_atributos_treino.values
resposta_treino = df_resposta_treino.values

atributos_teste = df_atributos_teste.values
resposta_teste = df_resposta_teste.values




# # Aplicar SMOTE no conjunto de treino, ajustando o número de vizinhos para evitar o erro
# smote = SMOTE(random_state=12, k_neighbors=1)
# atributos_treino, resposta_treino = smote.fit_resample(df_atributos_treino, df_resposta_treino)

# # Convertendo para arrays
# atributos_teste = df_atributos_teste.values
# resposta_teste = df_resposta_teste.values

In [8]:
classificador_bayes = GaussianNB()
modelo = classificador_bayes.fit(df_atributos_treino, df_resposta_treino)

probabilidades = classificador_bayes.predict_proba(atributos_teste)
classificacao = classificador_bayes.predict(atributos_teste)

c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [9]:
# print("Probabilidades das classes para os dados de teste:\n", probabilidades)
# print("Classificação dos dados de teste:\n", classificacao)

taxa_de_acerto = accuracy_score(resposta_teste, classificacao)
print("Taxa de acerto", taxa_de_acerto)
print("\nRelatório de Classificação:\n", classification_report(resposta_teste, classificacao))
print("Matriz de Confusão:\n", confusion_matrix(resposta_teste, classificacao))

Taxa de acerto 0.6190476190476191

Relatório de Classificação:
               precision    recall  f1-score   support

           0       0.75      0.30      0.43        10
           1       0.59      0.91      0.71        11

    accuracy                           0.62        21
   macro avg       0.67      0.60      0.57        21
weighted avg       0.67      0.62      0.58        21

Matriz de Confusão:
 [[ 3  7]
 [ 1 10]]


In [10]:
numfolds = 5
gnb = GaussianNB()

kf = KFold(n_splits=numfolds, shuffle=True, random_state=12)

validaçãoCruzada = cross_val_score(gnb, df_atributo, df_resposta, cv=kf)
media = validaçãoCruzada.mean()

print(validaçãoCruzada)
print(media)

[0.64705882 0.82352941 0.8125     0.875      1.        ]
0.8316176470588236


c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-pack

In [11]:
predictions = cross_val_predict(gnb, df_atributo, df_resposta, cv=kf)

fold_indices = np.arange(len(predictions)) % numfolds

conf_matrices = [
    confusion_matrix(df_resposta[fold_indices == i], predictions[fold_indices == i])
    for i in range(numfolds)
]

acuracia_matrices = [
    accuracy_score(df_resposta[fold_indices == i], predictions[fold_indices == i])
    for i in range(numfolds)
]

for i, conf_matrix in enumerate(conf_matrices):
    print(f"Fold {i + 1}:\nAcurácia: {round(acuracia_matrices[i]*100)}%\n{conf_matrix}\n")

mean_conf_matrix = np.mean(conf_matrices, axis=0)
mean_acuracia_matrix = np.mean(acuracia_matrices, axis=0)
print("matriz de confusao média:")
print(f"{mean_acuracia_matrix*100:.2f}%")
print(mean_conf_matrix)

Fold 1:
Acurácia: 100%
[[ 7  0]
 [ 0 10]]

Fold 2:
Acurácia: 71%
[[6 3]
 [2 6]]

Fold 3:
Acurácia: 94%
[[7 0]
 [1 8]]

Fold 4:
Acurácia: 88%
[[9 2]
 [0 5]]

Fold 5:
Acurácia: 62%
[[4 3]
 [3 6]]

matriz de confusao média:
82.87%
[[6.6 1.6]
 [1.2 7. ]]


c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lucalucareli-ieg\AppData\Local\Programs\Python\Python312\Lib\site-pack